# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Social Media Reader
#email: your-email@domain.com
description: >
  With the rise of web 2.0 and social media platforms taking over vast tracts of territory on the internet, the media landscape has shifted drastically in the past 20 years, transforming previously stable relationships between media creators and consumers. The Social Media Reader is the first collection to address the collective transformation with pieces on social media, peer production, copyright politics, and other aspects of contemporary internet culture from all the major thinkers in the field. 
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TheSocialMediaReader.cloudread.it" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'Michael Mandiberg'
bio: >
   'Michael Mandiberg' (born December 22, 1977) is an United States|American artist, programmer, designer and educator. Mandiberg describes himself as "an appropriationist at heart. I derive visual inspiration from the Internet, conceptual art, design, the end of print and the dying American empire. My work is both formal and poetic. I use words and symbols as tools to provoke reflection on our society and its effluvia." His works have been exhibited at venues including the New Museum|New Museum for Contemporary Art located in New York City, transmediale Festival in Berlin, Center for Art and Media Karlsruhe (ZKM) in Karlsruhe, Germany, and Ars Electronica Center located in Linz, Austria.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
