# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Last of the Mohicans
#email: your-email@domain.com
description: >
  The Last of the Mohicans, A Narrative of 1757 (1826) is a historical novel by James Fenimore Cooper. The novel is set primarily in the upper New York wilderness, detailing the transport of the two daughters of Colonel Munro, Alice and Cora, to a safe destination at Fort William Henry. 
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thelastofthemohicans.cloudread.it" # the base hostname & protocol for your site
paginate:	50 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'James Fenimore Cooper'
bio: >
  James Fenimore Cooper (September 15, 1789 – September 14, 1851) was a prolific and popular American writer of the first half of the 19th century. His historical romances draw a picture of frontier and American Indian life in the early American days which created a unique form of American literature. He lived most of his life in Cooperstown, New York, which was founded by his father William on property that he owned. Cooper was a lifelong member of the Episcopal Church and contributed generously to it.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
