# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Introducing Marketing
#email: your-email@domain.com
description: >
  This book demonstrates how companies use marketing. Specific examples appear not only in text discussions, but also in the chapter openers, Learning is not always about success stories. Diagnosing problems and failures is an important aspect of critical thinking, and examples of such are introduced to challenge students to learn from others' mistakes and better manage real-world problems.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marketing.cloudread.it" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'John Burnett'
bio: >
  Professor John Burnett is the author/co-author of twenty books and over 60 academic articles. He recently retired after 41 years as a professor of marketing and lives in Carlsbad, California. For the last twenty years much of his focus has been on marketing for nonprofits. The result has been numerous workshops, the creation of several marketing plans, and the book entitled, Nonprofit Marketing Best Practices.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
