# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everything You Ever Really Needed to Know About Personal Finance on Just One Page
#email: your-email@domain.com
hreflang: en-US
description: >
  Everything you really need to know abut personal finance can be summarized in just one page. Spend less than you earn. Earn more. Live frugal. Do something sensible with the difference. Control your own destiny. All of the other writing out there on personal finance is just details.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://personalfinance.cloudread.it" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'Hamm Trent'
bio: >
  I was born in raised in downstate rural Illinois. Growing up, my family didn't have a lot of money, but they did have a lot of love. They taught me the value of living frugally, but it wasn't always coupled with great financial lessons. In short, I had little idea how to manage my own money, and when I left home for college, I made a long sequence of financial mistakes.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
