# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Jungle Book
#email: your-email@domain.com
hreflang: en-US
description: >
  The Jungle Book (1894) is a collection of stories by the English author Rudyard Kipling. Most of the characters are animals such as Shere Khan the tiger and Baloo the bear, though a principal character is the boy or "man-cub" Mowgli, who is raised in the jungle by wolves. The stories are set in a forest in India; one place mentioned repeatedly is "Seonee" (Seoni), in the central state of Madhya Pradesh.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thejunglebook.cloudread.it" # the base hostname & protocol for your site
paginate:	50 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'Rudyard Kipling'
bio: >
  Joseph Rudyard Kipling (30 December 1865 – 18 January 1936) was an English journalist, short-story writer, poet, and novelist. Kipling's works of fiction include The Jungle Book (1894), Kim (1901), and many short stories, including "The Man Who Would Be King" (1888). His poems include "Mandalay" (1890), "Gunga Din" (1890), "The Gods of the Copybook Headings" (1919), "The White Man's Burden" (1899), and "If—" (1910). He is regarded as a major innovator in the art of the short story;
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
