# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Common Sense, How To Exercise It
#email: your-email@domain.com
description: >
  This eBook is for the use of anyone
  anywhere at no cost and with almost no restrictions whatsoever. You may
  copy it, give it away or re-use it under the terms of the Project
  Gutenberg License included with this eBook or online at
  www.gutenberg.net
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://commonsense.cloudread.it" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'Yoritomo-Tashi'
bio: >
  Yoritomo Tashi was a Japanese philosopher of the twelfth century, widely recognized and admired by his people and one of the greatest statesmen Japan has ever had.
  Tashi worked as a high official for the Japanese state, as a proofreader and editor of the laws of the empire, as well as being one of the organizers of military feudalism, and remarkably influenced his time and the mind of his people, with his public performances and his philosophy, rescuing his country from the lack of principles in which he was.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
