# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MANUAL DE URBANIDAD Y BUENAS MANERAS
#email: your-email@domain.com
hreflang: es-ES
description: >
  El Manual de urbanidad y buenas maneras o Manual de Carreño, fue escrito por Manuel Antonio Carreño en Venezuela en 1853. Esta obra contiene "lecciones y consejos" sobre cómo deben comportarse las personas en lugares públicos y privados tales como el hogar, la familia, la escuela y el trabajo.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manualdeurbanidad.cloudread.it" # the base hostname & protocol for your site
paginate:	50 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'Manuel A. Carreño'
bio: >
    Manuel Antonio del Rosario Carreño Muñoz (Caracas, 17 de junio de 1812 - París, 4 de septiembre de 1874) fue un músico, pedagogo y diplomático venezolano.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
