# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frankeinstein
#email: your-email@domain.com
hreflang: en-US
description: >
  Frankenstein; or, The Modern Prometheus is a novel written by English author Mary Shelley (1797–1851) that tells the story of Victor Frankenstein, a young scientist who creates a grotesque but sapient creature in an unorthodox scientific experiment.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frankenstein.cloudread.it" # the base hostname & protocol for your site
paginate:	50 # The number of posts to show per page on your homepage
permalink: /chapter/:title/
name: 'Mary Shelley'
bio: >
    Mary Wollstonecraft Shelley (née Godwin; 30 August 1797 – 1 February 1851) was an English novelist, short story writer, dramatist, essayist, biographer, and travel writer, best known for her Gothic novel Frankenstein or, The Modern Prometheus (1818). She also edited and promoted the works of her husband, the Romantic poet and philosopher Percy Bysshe Shelley. Her father was the political philosopher William Godwin, and her mother was the philosopher and feminist Mary Wollstonecraft.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap

image:
  src: '/assets/images/banner.jpg'
  height: 630
  width: 1200
  type: image/jpeg