# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Law of Success in Sixteen Lessons
#email: your-email@domain.com
description: >
  The original monumental success masterpiece which clearly delineates the qualities which you must possess to become an over-achiever.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lawofsuccess.cloudread.it" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage
permalink: /lesson/:title/
name: 'Oliver Napoleon Hill'
bio: >
  'Oliver Napoleon Hill' (born October 26, 1883 – November 8, 1970) was an American self-help author. He is known best for his book ''Think and Grow Rich'' (1937) which is among the 10 best selling self-help books of all time. Hill's works insisted that fervid expectations are essential to improving one's life. Most of his books were promoted as expounding principles to achieve "success".
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: "UA-119872433-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
